version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qwint-admin-frontend
    ports:
      - "${PORT:-8080}:${PORT:-80}"
    environment:
      - PORT=${PORT:-80}
    restart: unless-stopped
    labels:
      - 'caddy_0.basicauth=/*'
      - 'caddy_0.basicauth.qwintsoft=$$2b$$10$$oCFVXBLwDD9evlwd7eEvU.h5r2fl3yJkOjnqyB.XpFi3NO3uWHOnm'
